import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {

  // -----------------------------
  // Functional Specifications
  // -----------------------------
 functionalSpecificationsSidebar: [
  {
    type: 'category',
    label: 'Functional Specifications',
    link: { type: 'doc', id: 'functional-specifications/index' },
    collapsed: false,
    items: [
      {
        type: 'category',
        label: 'Financial',
        collapsed: true,
        items: [
          'functional-specifications/financial/ibft-incoming-title-fetch',
          'functional-specifications/financial/ibft-credit-request',
          'functional-specifications/financial/outward-title-fetch-account',
          'functional-specifications/financial/outward-transfers-ibft',
          'functional-specifications/financial/wallet-wallet-title-fetch',
          'functional-specifications/financial/wallet-wallet-transfers',
          'functional-specifications/financial/raast-incoming-title-fetch',
          'functional-specifications/financial/raast-incoming-credit-request',
          'functional-specifications/financial/raast-outward-title-fetch',
          'functional-specifications/financial/raast-pay-via-id',
          'functional-specifications/financial/outward-title-fetch-iban',
          'functional-specifications/financial/raast-payment-flow',
          'functional-specifications/financial/bill-inquiry',
          'functional-specifications/financial/bill-payment',
        ],
      },
      {
        type: 'category',
        label: 'Non-Financial',
        collapsed: true,
        items: [
          'functional-specifications/non-financial/index'
          // add more later
        ],
      },
    ],
  },
],

  // -----------------------------
  // Backoffice Sidebar
  // -----------------------------
  backofficeSidebar: [
    {
      type: 'doc',
      id: 'backoffice/get-started',
      label: 'Get Started',
    },
    {
      type: 'category',
      label: 'General Ledger',
      items: [
        'backoffice/general-ledger/chart-of-accounts',
        'backoffice/general-ledger/gl-posting',
        'backoffice/general-ledger/journal-in',
        'backoffice/general-ledger/journal-out',
      ],
    },
    {
      type: 'category',
      label: 'Product Management',
      items: [
        'backoffice/product-management/product-group',
        'backoffice/product-management/product-configuration',
        'backoffice/product-management/kyc-group',
        'backoffice/product-management/product-fee-setup',
        'backoffice/product-management/product-tax-setup',
      ],
    },
    {
      type: 'category',
      label: 'Transaction Management',
      items: [
        'backoffice/transaction-management/customer-posting',
        'backoffice/transaction-management/transaction-reversal',
        'backoffice/transaction-management/lien-marking',
        'backoffice/transaction-management/transaction-monitoring',
      ],
    },
    {
      type: 'category',
      label: 'Customer Management',
      items: [
        'backoffice/customer-management/customer-information',
        'backoffice/customer-management/call-center',
        'backoffice/customer-management/customer-due-diligence',
        'backoffice/customer-management/enhanced-due-diligence',
      ],
    },
    {
      type: 'doc',
      id: 'backoffice/audit-management',
      label: 'Audit Management',
    },
  ],

  // -----------------------------
  // Default autogenerated sidebar
  // -----------------------------
  
};

export default sidebars;
